### PR TITLE
changed override root paths

### PR DESCRIPTION
**Pull request by linkanon**
/aa2g/ discussed this a few times. As it is you'd either have to store some meshes and non-texture files in `\data\texture\override` or have to split overrides in different places. This pull request simply moves the `OVERRIDE_IMAGE_PATH` and `OVERRIDE_ARCHIVE_PATH` in the same place so all overrides are kept in a single location. Imo ideally is to let user set the overrides location in the `config.txt` but I wanted @AA2Hackanon's input on this first. If you're fine with it I can try making it configurable for this PR.

Semi-related but I didn't get how tans are supposed to work here. Do you have to set the `TAN_PATH`'s structure akin to `tantoo`'s?

### CODE REVIEW

**Comment by linkanon** [comment]
Additionally here's an example of the folder structure for all the override assets that a few people agreed to:
AA2_MAKE\data\textures\override\
├ body_textures\
├ face_textures\
├ hair_highlights\
├ hair_textures\
├ Meshes\
│ ├ face\
│ ├ hair\
│ ├ body\
│ └ clothes\
├ PP\
│ └ sclera_textures\
└ Tans\
   ├ face\
   ├ body\
   ├ arms\
   └ nails\

One complaint was that it's too complicated but it's a matter of convention. As long as it's all in one place that makes sense.

**Comment by AA2Hackanon** [comment]
the reason why the image path was aaedit/texture/overrides is basically because aau started out as a way to apply hair highlights on a card-by-card basis, so i thought having them next to eye textures and stuff was a good idea. now that basically anything can be overriden, moving everything into a single folder is probably a good idea. 

being able to change it in the config txt sounds like a bad idea though, if only because it can "break" all aau related stuff just by changing the config.txt. enforcing a certain structure like above is hardly possible either since aau cant possibly differentiate between different kind of meshes, tans or textures. If you want to be able to move the folder around, try giving it a distinct name let aau look for it at the startup. Im not sure how much is implicitly assumed about the structure right now, so that might be a little work.

as for the tans, should be described in Texts/config.txt. essentially, copy the "tan" folder from tantoo into overrides, it looks for overrides/tan/nameoftan/00.bmp to 04.bmp and automatically applies generalized override rules if found, or an override rule with a hardcoded 1x1 transparent image if its not there.

**Comment by linkanon** [comment]
Configurable path is pretty much a feature no one wants or needs and is more trouble than its worth even though I suggested it.

No need to enforce the structure because it can be a pain in the ass if it's inconvenient. Enforcing everything to be under data\override is enough. That structure is a convention I and others came up with at least for now to keep the overrides from becoming a mess.

This PR requires a one-time adjustments to old AAU cards but it's not that difficult to do because there's not much AAU cards around for now. I would merge it right before v0.3 release.

**Comment by geneishouko** [comment]
The single directory for overrides could be a thing. I'd prefer it to be a thing but as I have not contributed to this, yet, I have no weigh on the matter. That said, if it goes it should offer backwards compatibility for old cards. Backwards compatibility like checking the old path if no file was found in the new one.

**Comment by linkanon** [comment]
imo backwards compatibility is not a priority now. Moving `texture\overrides` one level up might break some cards but only for the textures like sclera and hair highlights which is mostly unnoticeable and since there's not a lot of cards around it's easy to fix. Hair highlights are even less important because there's a special UI for them, they just don't get saved at the moment(for me at least) so in the future they should be done differently, like tans.
Since it can "break" some cards it warrants a major version increase.

**Comment by geneishouko** [comment]
This may be stupid of me to bring so late (I missed the whole span of changes) but can we reconsider the change of the root override path? This change broke every single AAU card. Merging them was ideal but the changes brought were severe.

To be clear, I'm okay with the merge but merging them to the previous root path.

**Pull request merged**
