### PR TITLE
misc stuff for v1.8.1

### PR DESCRIPTION
**Pull request by linkanon**
- added the jmcp script to the repo
- fixed mesh overrides not overwriting entries properly
- added checkbox to the launcher that lets you keep the PPeX window open

### CODE REVIEW

**Comment by sqauid37483** [comment]
Can someone create a module where npcs prefer certain H position.

**Comment by linkanon** [comment]
you mean just change the npcs' H preferences?

**Comment by sqauid37483** [comment]
I'm saying if I change to doggy style and the npc would stop sex. Thanks for replying tho.

**Comment by sqauid37483** [comment]
How do I patch the game with new version?

**Pull request merged**
